server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.21.225:3306/qianfeng?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
      force: true
      force-request: true
      enabled: true
  application:
    name: LoginProvider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath*:com/qianfeng/mapping/*.xml